[project]
name = "automacao-tarefas"
version = "0.1.0"
description = "Para facilitar as tarefas diárias"
authors = [
    {name = "Sarah Janne",email = "sarahjanne.enos@hotmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "pyautogui (>=0.9.54,<0.10.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
